/**
 * Build Configuration Script
 * 
 * This script generates js/env-config.js with environment variables.
 * Run this script during the build process on Cloudflare Pages.
 * 
 * Usage:
 *   npm run build
 * 
 * Environment Variables (set in Cloudflare Pages dashboard):
 *   - SUPABASE_URL: Your Supabase project URL
 *   - SUPABASE_ANON_KEY: Your Supabase anonymous key
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get environment variables with fallback to placeholder values
const SUPABASE_URL = process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || 'YOUR_SUPABASE_ANON_KEY';

// Generate the config file content
const configContent = `/**
 * Environment Configuration
 * 
 * This file is auto-generated during the build process.
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * To configure Supabase credentials:
 * 1. Set SUPABASE_URL and SUPABASE_ANON_KEY environment variables in Cloudflare Pages
 * 2. Run: npm run build
 * 
 * Generated at: ${new Date().toISOString()}
 */

window.ENV_CONFIG = {
    SUPABASE_URL: '${SUPABASE_URL}',
    SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}'
};
`;

// Write the config file
const outputPath = path.join(__dirname, '..', 'js', 'env-config.js');

try {
    fs.writeFileSync(outputPath, configContent, 'utf8');
    console.log('✅ Environment config generated successfully!');
    console.log(`   Output: ${outputPath}`);
    console.log(`   SUPABASE_URL: ${SUPABASE_URL === 'YOUR_SUPABASE_URL' ? '(not configured - using placeholder)' : '✓ configured'}`);
    console.log(`   SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY === 'YOUR_SUPABASE_ANON_KEY' ? '(not configured - using placeholder)' : '✓ configured'}`);
} catch (error) {
    console.error('❌ Failed to generate environment config:', error.message);
    process.exit(1);
}
